WINDOW_LENGTH=1000
SLIDE_DELTA=100
SUBCARRIERS=30
USE_PHASE=False
TAGS=('none', 'still', 'crouch', 'flipped', 'rolling')

MODEL_USE_ATTENTION=False
MODEL_UNITS_LSTM=200
MODEL_UNITS_ATTENTION=400

TRAIN_BATCH_SIZE=64
TRAIN_EPOCHS=10
TRAIN_LEARNING_RATE=1e-5